# Site settings
title: "Just another random webpage"
name: "Just another random webpage"
author: "Tiago Ferreira"
email: "tiagoferreira@fpce.up.pt"
description: "This is my personal webpage! Stay tuned for releases with new data analysis tutorials and code."
github_username: "tiagodsferreira"

# URL settings
url: "https://tiagodsferreira.github.io"   # main domain (no trailing slash, no project name)
baseurl: "/JARW"                           # repo/project name

# Plugins
plugins:
  - jekyll-feed

# Feed settings
feed:
  path: feed.xml
  limit: 10
  update_period: daily
  update_frequency: 1

# Build settings
theme: minima
markdown: kramdown
